/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendamentosRouteImport } from './routes/agendamentos'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentosRoute = AgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendamentos': typeof AgendamentosRoute
  '/buscar': typeof BuscarRoute
  '/conta': typeof ContaRoute
  '/entrar': typeof EntrarRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendamentos': typeof AgendamentosRoute
  '/buscar': typeof BuscarRoute
  '/conta': typeof ContaRoute
  '/entrar': typeof EntrarRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendamentos': typeof AgendamentosRoute
  '/buscar': typeof BuscarRoute
  '/conta': typeof ContaRoute
  '/entrar': typeof EntrarRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendamentos'
    | '/buscar'
    | '/conta'
    | '/entrar'
    | '/redefinir-senha'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendamentos'
    | '/buscar'
    | '/conta'
    | '/entrar'
    | '/redefinir-senha'
  id:
    | '__root__'
    | '/'
    | '/agendamentos'
    | '/buscar'
    | '/conta'
    | '/entrar'
    | '/redefinir-senha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendamentosRoute: typeof AgendamentosRoute
  BuscarRoute: typeof BuscarRoute
  ContaRoute: typeof ContaRoute
  EntrarRoute: typeof EntrarRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamentos': {
      id: '/agendamentos'
      path: '/agendamentos'
      fullPath: '/agendamentos'
      preLoaderRoute: typeof AgendamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendamentosRoute: AgendamentosRoute,
  BuscarRoute: BuscarRoute,
  ContaRoute: ContaRoute,
  EntrarRoute: EntrarRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
